log:
  level: debug
  disable_sentry: true
<%_ if (useDB) { _%>

db:
  url: db_url
<%_ } _%>
<%_ if (handleHTTP) { _%>

listener:
  addr: :8000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: <%= serviceName %>
  service_port: 80
<%_ } _%>
